language: ruby
rvm:
  - 1.9.3
  - 2.0.0
script: "bundle exec cucumber -r features"
notifications:
  recipients:
    - ben.biddington@gmail.com
    - plusjade@gmail.com
matrix:
  allow_failures:
    - rvm: 2.0.0
